export const DISPLAY_CONFIG = {
  TITLE_MAX_CHARS: 17,
  TITLE_SCROLL_START_DELAY_MS: 100,
  TITLE_SCROLL_INTERVAL_MS: 300,
  TITLE_SCROLL_PAUSE_AT_START: 16,
  TITLE_SCROLL_PAUSE_AT_END: 8,
  SCROLL_DIRECTION_FORWARD: 1,
  SCROLL_DIRECTION_BACKWARD: -1,
} as const;

export const SPARKLINE_CONFIG = {
  MAX_HISTORY_POINTS: 8,
  BAR_WIDTH: 3,
  BAR_GAP: 2,
  HEIGHT: 10,
  MIN_BAR_HEIGHT: 2,
  MIN_VALUE_TO_AVOID_DIVISION_BY_ZERO: 1,
  SVG_NAMESPACE: "http://www.w3.org/2000/svg",
  BORDER_RADIUS: "1",
} as const;

export const SVG_WIDTH =
  SPARKLINE_CONFIG.BAR_WIDTH * SPARKLINE_CONFIG.MAX_HISTORY_POINTS +
  SPARKLINE_CONFIG.BAR_GAP * (SPARKLINE_CONFIG.MAX_HISTORY_POINTS - 1);

