export const DISPLAY_CONFIG = {
  TITLE_MAX_CHARS: 17,
  TITLE_SCROLL_START_DELAY_MS: 100,
  TITLE_SCROLL_INTERVAL_MS: 300,
  TITLE_SCROLL_PAUSE_AT_START: 16,
  TITLE_SCROLL_PAUSE_AT_END: 8,
  SCROLL_DIRECTION_FORWARD: 1,
  SCROLL_DIRECTION_BACKWARD: -1,
} as const;
