export const SPARKLINE_CONFIG = {
  MAX_HISTORY_POINTS: 8,
  BAR_WIDTH: 3,
  BAR_GAP: 2,
  HEIGHT: 10,
  MIN_BAR_HEIGHT: 2,
  MIN_VALUE_TO_AVOID_DIVISION_BY_ZERO: 1,
  SVG_NAMESPACE: "http://www.w3.org/2000/svg",
  BORDER_RADIUS: "1",
} as const;

export const SVG_WIDTH =
  SPARKLINE_CONFIG.BAR_WIDTH * SPARKLINE_CONFIG.MAX_HISTORY_POINTS +
  SPARKLINE_CONFIG.BAR_GAP * (SPARKLINE_CONFIG.MAX_HISTORY_POINTS - 1);
